export const REQUES_METHOD = "METHOD/REQUES_METHOD"
export const GET_URL = "METHOD/GET_METHOD"

export const SHOW_ALERT = "APP/SHOW_ALERT"
export const HIDE_ALERT = "APP/HIDE_ALERT"

export const FETCHED_DATA = "APP/FETCHED_DATA"

export const SHOW_LOADER = "LOADER/SHOW_LOADER"
export const HIDE_LOADER = "LOADER/HIDE_LOADER"